# Generated by Django 5.2.15 on 2026-07-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Пропущен')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped', to='teacher_rank.person', verbose_name='Пользователь')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped', to='teacher_rank.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пропущенный преподаватель',
                'verbose_name_plural': 'Пропущенные преподаватели',
                'ordering': ['-created_at'],
                'unique_together': {('person', 'teacher')},
            },
        ),
    ]
