# Generated by Django 5.2.15 on 2026-07-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rank', '0002_skippedteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'ordering': ['course__number', 'subject__name'], 'verbose_name': 'Предмет преподавателя', 'verbose_name_plural': 'Предметы преподавателей'},
        ),
        migrations.CreateModel(
            name='RatingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎')], verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлена')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_likes', to='teacher_rank.person', verbose_name='Пользователь')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='teacher_rank.rating', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Лайк/дизлайк',
                'verbose_name_plural': 'Лайки/дизлайки',
                'ordering': ['-created_at'],
                'unique_together': {('person', 'rating')},
            },
        ),
    ]
