# Generated by Django 5.2.15 on 2026-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rank', '0003_add_rating_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимно'),
        ),
    ]
