# Generated by Django 5.2.15 on 2026-07-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rank', '0004_add_anonymous_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='easy_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Халявность'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Качество обучения'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vibe_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Вайбовость'),
        ),
    ]
